# Generated by Django 2.1.15 on 2022-11-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('apellido_usuario', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('ultima_conexion', models.DateTimeField(verbose_name='fecha ultma conexion')),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
