# Generated by Django 2.1.15 on 2022-11-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_remove_usuarios_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Conversaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Usuarios')),
            ],
            options={
                'db_table': 'Participantes',
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='id_conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Conversaciones'),
        ),
        migrations.AddField(
            model_name='chats',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Usuarios'),
        ),
    ]
