# Generated by Django 2.1.15 on 2022-11-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0004_auto_20221116_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='id_conversacion',
            field=models.IntegerField(default=0),
        ),
    ]
