# Generated by Django 2.1.15 on 2022-11-17 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0005_participantes_id_conversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='id_conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Conversaciones'),
        ),
    ]
